dependencies {
  api "com.badlogicgames.gdx:gdx-bullet:$gdxVersion"
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  implementation "space.earlygrey:shapedrawer:$shapedrawerVersion"


  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
}